import { AXES, defaultPresetOf, assertAxisIntegrity } from '../axes/registry.ts';

/** Small, DOM-free public configuration helpers generated from the actual registry. */
export function emitConfig(): string {
  assertAxisIntegrity();
  const presets=Object.fromEntries(AXES.map(axis=>[axis.id,axis.presets.map(p=>p.id)]));
  const defaults=Object.fromEntries(AXES.map(axis=>[axis.id,defaultPresetOf(axis).id]));
  return `// Generated by Area. Do not edit.
export const AXIS_PRESETS = Object.freeze(Object.fromEntries(Object.entries(${JSON.stringify(presets)}).map(([key,values])=>[key,Object.freeze(values)])));
export const DEFAULT_AXES = Object.freeze(${JSON.stringify(defaults)});

export function mergeAxes(parent = DEFAULT_AXES, overrides = {}) {
  const result = { ...DEFAULT_AXES };
  for (const selection of [parent, overrides]) {
    if(selection === null || typeof selection !== "object" || Array.isArray(selection)) throw new TypeError("Area selections must be objects.");
    for (const [axis, value] of Object.entries(selection)) {
    if (!Object.hasOwn(AXIS_PRESETS, axis)) throw new RangeError('Unknown Area axis: ' + axis);
    if (value === undefined) continue;
    if (!AXIS_PRESETS[axis].includes(value)) throw new RangeError('Unknown Area preset: ' + axis + '=' + value);
    result[axis] = value;
  }
  }
  return Object.freeze(result);
}

export function themeAttributes(selection = DEFAULT_AXES) {
  return Object.fromEntries(Object.entries(mergeAxes(DEFAULT_AXES, selection)).map(([axis,value])=>['data-area-'+axis,value]));
}
`;
}

export function emitConfigTypes(): string {
  return `// Generated from the Area registry. Do not edit.
export interface AxisSelection {
${AXES.map(axis=>`  ${axis.id}: ${axis.presets.map(p=>JSON.stringify(p.id)).join(' | ')};`).join('\n')}
}
export declare const AXIS_PRESETS: Readonly<{ [K in keyof AxisSelection]: readonly AxisSelection[K][] }>;
export declare const DEFAULT_AXES: Readonly<AxisSelection>;
export declare function mergeAxes(parent?: Partial<AxisSelection>, overrides?: Partial<AxisSelection>): Readonly<AxisSelection>;
export declare function themeAttributes(selection?: Partial<AxisSelection>): { [K in keyof AxisSelection as \`data-area-\${K}\`]: AxisSelection[K] };
`;
}
