/**
 * Type declarations for the public token surface.
 *
 * Gives consumers autocomplete on inline overrides:
 *   style={{ "--area-radius-control": "10px" } as React.CSSProperties}
 *
 * and makes a typo in a token name a compile error instead of a silently ignored
 * declaration -- which is otherwise invisible, because CSS drops unknown properties.
 */
import { AXES } from "../axes/registry.ts";
import { baseTokens, derivedTokens } from "./base.ts";

export function emitTypes(): string {
  const names = new Set<string>([...Object.keys(baseTokens()), ...Object.keys(derivedTokens())]);
  for (const axis of AXES) {
    for (const preset of axis.presets) {
      for (const key of Object.keys(preset.tokens)) names.add(key);
    }
  }

  const sorted = [...names].sort();
  const axisUnions = AXES.map(
    (axis) =>
      `export type Area${pascal(axis.id)}Preset =\n${axis.presets
        .map((p) => `  | "${p.id}"`)
        .join("\n")};`,
  ).join("\n\n");

  return [
    "// Generated by @area/tokens. Do not edit.",
    "",
    "/** Every custom property Area defines. */",
    "export type AreaToken =",
    ...sorted.map((n) => `  | "${n}"`),
    ";",
    "",
    "/** The presets available on each axis. */",
    axisUnions,
    "",
    "/** The data attributes that select an axis preset. */",
    "export interface AreaAxisAttributes {",
    ...AXES.map((a) => `  "data-area-${a.id}"?: Area${pascal(a.id)}Preset;`),
    "}",
    "",
  ].join("\n");
}

function pascal(id: string): string {
  return id.replace(/(^|-)([a-z])/g, (_, __, c: string) => c.toUpperCase());
}
