#!/usr/bin/env python3
"""Look up measured evidence for one Area component across every system.

  python3 lookup.py badge            numbers-only view, every system
  python3 lookup.py badge --full     full evidence files
  python3 lookup.py badge --sys pri,flu
  python3 lookup.py --find toggle    search file names in every system
  python3 lookup.py --list           components known to components.json
  python3 lookup.py --reindex        rewrite ../../evidence/INDEX.md
"""
import os, re, sys, json, signal
signal.signal(signal.SIGPIPE, signal.SIG_DFL)
HERE = os.path.dirname(os.path.abspath(__file__))
EV = os.path.abspath(os.path.join(HERE, "..", "..", "evidence"))
COMP = {k: v for k, v in json.load(open(os.path.join(HERE, "components.json"))).items() if not k.startswith("_")}
SYS = [d for d in sorted(os.listdir(EV)) if os.path.isdir(os.path.join(EV, d))] if os.path.isdir(EV) else []
NUM = re.compile(r"\d(px|rem|em|%)|: \d[\d.]*[,;]?\s*(//.*)?$|: \d+ [*/]|=> |/\* = |size|small|medium|large|tiny|'(xs|sm|md|lg|xl)'|\b(xs|sm|md|lg|xl|2xl|3xl)\b.*\{|RADIUS|^  [\w\"']+:|^\s+L\d+|^###|shape|typograph", re.I)
NOISE = re.compile(r"color|background|shadow|transition|opacity|z-index|animation|stroke-dash|@media|cursor|outline-color|fill:", re.I)

def files_for(slug):
    pats = [re.compile(p, re.I) for p in COMP.get(slug, [re.escape(slug)])]
    out = {}
    for s in SYS:
        hits = [f[:-4] for f in sorted(os.listdir(os.path.join(EV, s))) if f.endswith(".txt") and any(p.search(f[:-4]) for p in pats)]
        if hits: out[s] = hits
    return out

def show(slug, full, only):
    found = files_for(slug)
    if not found: print(f"no evidence files matched '{slug}'. Try: lookup.py --find {slug}"); return
    for s in SYS:
        if only and s not in only: continue
        if s not in found: print(f"\n===== {s}: no file (record as n/p for this system, or add a pattern to components.json)"); continue
        for name in found[s]:
            print(f"\n===== {s}/{name}.txt")
            for line in open(os.path.join(EV, s, name + ".txt"), errors="ignore"):
                line = line.rstrip("\n")
                if not line.strip(): continue
                if full or (NUM.search(line) and not NOISE.search(line)):
                    print(re.sub(r"\s+", " ", line)[:200] if not full else line)

def reindex():
    rows = ["# Evidence index", "", "Generated by `python3 tools/audit-evidence/lookup.py --reindex` from `components.json`. One row per Area component: the evidence files to read in each system. An empty cell means that system has no such component in the pinned source: record it as `n/p`.", "", "| Component | " + " | ".join(SYS) + " |", "| --- |" + " --- |" * len(SYS)]
    for slug in COMP:
        f = files_for(slug)
        rows.append(f"| `{slug}` | " + " | ".join(", ".join(f.get(s, [])) for s in SYS) + " |")
    open(os.path.join(EV, "INDEX.md"), "w").write("\n".join(rows) + "\n"); print("wrote", os.path.join(EV, "INDEX.md"))

a = sys.argv[1:]
if not a or a[0] in ("-h", "--help"): print(__doc__)
elif a[0] == "--list": print("\n".join(COMP))
elif a[0] == "--reindex": reindex()
elif a[0] == "--find":
    p = re.compile(a[1], re.I)
    for s in SYS:
        hits = [f[:-4] for f in sorted(os.listdir(os.path.join(EV, s))) if p.search(f)]
        if hits: print(f"{s}: {', '.join(hits)}")
else:
    only = a[a.index("--sys") + 1].split(",") if "--sys" in a else None
    show(a[0], "--full" in a, only)
